version: '3'
services:
  web-amazonlinux:
    image: web-amazonlinux
    container_name: web-amazonlinux
    build:
      context: ./amazonlinux/
      dockerfile: app.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_APP}:/data
