version: '3'
services:
  web:
    image: web
    build:
      context: ./amazonlinux/
      dockerfile: app.dockerfile
    container_name: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /www:/data
